//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace JetBrains.Rider.Model
{
  
  
  /// <summary>
  /// <p>Generated from: ResxFormatterModel.kt:12</p>
  /// </summary>
  public class ResxFormatterModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IRdEndpoint<RdResxFormatterFormattingRequest, RdResxFormatterFormattingResult> PerformReformat => _PerformReformat;
    
    //private fields
    [NotNull] private readonly RdCall<RdResxFormatterFormattingRequest, RdResxFormatterFormattingResult> _PerformReformat;
    
    //primary constructor
    private ResxFormatterModel(
      [NotNull] RdCall<RdResxFormatterFormattingRequest, RdResxFormatterFormattingResult> performReformat
    )
    {
      if (performReformat == null) throw new ArgumentNullException("performReformat");
      
      _PerformReformat = performReformat;
      _PerformReformat.Async = true;
      BindableChildren.Add(new KeyValuePair<string, object>("performReformat", _PerformReformat));
    }
    //secondary constructor
    internal ResxFormatterModel (
    ) : this (
      new RdCall<RdResxFormatterFormattingRequest, RdResxFormatterFormattingResult>(RdResxFormatterFormattingRequest.Read, RdResxFormatterFormattingRequest.Write, RdResxFormatterFormattingResult.Read, RdResxFormatterFormattingResult.Write)
    ) {}
    //deconstruct trait
    //statics
    
    
    
    protected override long SerializationHash => -6843957654235836186L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(IdeRoot), IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("ResxFormatterModel (");
      using (printer.IndentCookie()) {
        printer.Print("performReformat = "); _PerformReformat.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class SolutionResxFormatterModelEx
   {
    public static ResxFormatterModel GetResxFormatterModel(this Solution solution)
    {
      return solution.GetOrCreateExtension("resxFormatterModel", () => new ResxFormatterModel());
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ResxFormatterModel.kt:14</p>
  /// </summary>
  public sealed class RdResxFormatterFormattingRequest : IPrintable, IEquatable<RdResxFormatterFormattingRequest>
  {
    //fields
    //public fields
    [NotNull] public string FilePath {get; private set;}
    [NotNull] public string DocumentText {get; private set;}
    
    //private fields
    //primary constructor
    public RdResxFormatterFormattingRequest(
      [NotNull] string filePath,
      [NotNull] string documentText
    )
    {
      if (filePath == null) throw new ArgumentNullException("filePath");
      if (documentText == null) throw new ArgumentNullException("documentText");
      
      FilePath = filePath;
      DocumentText = documentText;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string filePath, [NotNull] out string documentText)
    {
      filePath = FilePath;
      documentText = DocumentText;
    }
    //statics
    
    public static CtxReadDelegate<RdResxFormatterFormattingRequest> Read = (ctx, reader) => 
    {
      var filePath = reader.ReadString();
      var documentText = reader.ReadString();
      var _result = new RdResxFormatterFormattingRequest(filePath, documentText);
      return _result;
    };
    
    public static CtxWriteDelegate<RdResxFormatterFormattingRequest> Write = (ctx, writer, value) => 
    {
      writer.Write(value.FilePath);
      writer.Write(value.DocumentText);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdResxFormatterFormattingRequest) obj);
    }
    public bool Equals(RdResxFormatterFormattingRequest other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return FilePath == other.FilePath && DocumentText == other.DocumentText;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + FilePath.GetHashCode();
        hash = hash * 31 + DocumentText.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdResxFormatterFormattingRequest (");
      using (printer.IndentCookie()) {
        printer.Print("filePath = "); FilePath.PrintEx(printer); printer.Println();
        printer.Print("documentText = "); DocumentText.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ResxFormatterModel.kt:19</p>
  /// </summary>
  public sealed class RdResxFormatterFormattingResult : IPrintable, IEquatable<RdResxFormatterFormattingResult>
  {
    //fields
    //public fields
    public bool IsSuccess {get; private set;}
    public bool HasUpdated {get; private set;}
    [NotNull] public string FormattedText {get; private set;}
    
    //private fields
    //primary constructor
    public RdResxFormatterFormattingResult(
      bool isSuccess,
      bool hasUpdated,
      [NotNull] string formattedText
    )
    {
      if (formattedText == null) throw new ArgumentNullException("formattedText");
      
      IsSuccess = isSuccess;
      HasUpdated = hasUpdated;
      FormattedText = formattedText;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out bool isSuccess, out bool hasUpdated, [NotNull] out string formattedText)
    {
      isSuccess = IsSuccess;
      hasUpdated = HasUpdated;
      formattedText = FormattedText;
    }
    //statics
    
    public static CtxReadDelegate<RdResxFormatterFormattingResult> Read = (ctx, reader) => 
    {
      var isSuccess = reader.ReadBool();
      var hasUpdated = reader.ReadBool();
      var formattedText = reader.ReadString();
      var _result = new RdResxFormatterFormattingResult(isSuccess, hasUpdated, formattedText);
      return _result;
    };
    
    public static CtxWriteDelegate<RdResxFormatterFormattingResult> Write = (ctx, writer, value) => 
    {
      writer.Write(value.IsSuccess);
      writer.Write(value.HasUpdated);
      writer.Write(value.FormattedText);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdResxFormatterFormattingResult) obj);
    }
    public bool Equals(RdResxFormatterFormattingResult other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return IsSuccess == other.IsSuccess && HasUpdated == other.HasUpdated && FormattedText == other.FormattedText;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + IsSuccess.GetHashCode();
        hash = hash * 31 + HasUpdated.GetHashCode();
        hash = hash * 31 + FormattedText.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdResxFormatterFormattingResult (");
      using (printer.IndentCookie()) {
        printer.Print("isSuccess = "); IsSuccess.PrintEx(printer); printer.Println();
        printer.Print("hasUpdated = "); HasUpdated.PrintEx(printer); printer.Println();
        printer.Print("formattedText = "); FormattedText.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
