//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResxFormatter.Extension.Rider.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResxFormatter.Extension.Rider.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External configuration file:.
        /// </summary>
        internal static string ExternalConfigurationFile {
            get {
                return ResourceManager.GetString("ExternalConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines location of external Resx Formatter configuration file. Specifying an external configuration file allows you to easily point multiple instances to a shared configuration. The configuration path can be local or network-based. Invalid configurations will be ignored..
        /// </summary>
        internal static string ExternalConfigurationFileToolTip {
            get {
                return ResourceManager.GetString("ExternalConfigurationFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Visual Studio ResxFormatter Settings.
        /// </summary>
        internal static string ImportResxFormatterEditorConfig {
            get {
                return ResourceManager.GetString("ImportResxFormatterEditorConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read ResxFormatter settings from .editorconfig, if available.
        ///Overwrites all other settings..
        /// </summary>
        internal static string ImportResxFormatterEditorConfigToolTip {
            get {
                return ResourceManager.GetString("ImportResxFormatterEditorConfigToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key order:.
        /// </summary>
        internal static string KeyOrder {
            get {
                return ResourceManager.GetString("KeyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove documentation comment from resx file.
        /// </summary>
        internal static string RemoveDocumentationComment {
            get {
                return ResourceManager.GetString("RemoveDocumentationComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove XSD schema from resx file.
        /// </summary>
        internal static string RemoveXsdSchema {
            get {
                return ResourceManager.GetString("RemoveXsdSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search to drive root.
        /// </summary>
        internal static string SearchToDriveRoot {
            get {
                return ResourceManager.GetString("SearchToDriveRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When set to true, Resx Formatter will look for an external Resx Formatter configuration file not only up through your solution directory, but up through the drives root of the current solution so you can share one configuration file through multiple solutions..
        /// </summary>
        internal static string SearchToDriveRootToolTip {
            get {
                return ResourceManager.GetString("SearchToDriveRootToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Resx file.
        /// </summary>
        internal static string SortResxFile {
            get {
                return ResourceManager.GetString("SortResxFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Resx files in project.
        /// </summary>
        internal static string SortResxFilesInProject {
            get {
                return ResourceManager.GetString("SortResxFilesInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Resx files in solution.
        /// </summary>
        internal static string SortResxFilesInSolution {
            get {
                return ResourceManager.GetString("SortResxFilesInSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort resx on save.
        /// </summary>
        internal static string SortResxOnSave {
            get {
                return ResourceManager.GetString("SortResxOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines whether to automatically format the active resx file while saving..
        /// </summary>
        internal static string SortResxOnSaveToolTip {
            get {
                return ResourceManager.GetString("SortResxOnSaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort with Resx Formatter.
        /// </summary>
        internal static string SortWithResxFormatter {
            get {
                return ResourceManager.GetString("SortWithResxFormatter", resourceCulture);
            }
        }
    }
}
